---

- name: Cargamos las variables del entorno {{ entorno }}
  include_vars: "{{ entorno }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ dir_base }}"
    - "{{ dir_work }}"
    - "{{ dir_log }}"

- name: var files
  template:
    src: get-dockerhub-images.cfg.j2
    dest: "{{ dir_base }}/get-dockerhub-images.cfg"
    mode: 0775

- name: template get-dockerhub-images
  template:
    src: get-dockerhub-images.sh.j2
    dest: "{{ dir_base }}/get-dockerhub-images.sh"
    mode: 0775
